# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83641758d346a206e08c6fe65b5d469d02247413fe4b154e595219fe5cf15a7494b942ba66841c1cdefaf325864ff7cbf643ab42b44640dd9472964a455ee294

test:
  secret_key_base: 70cd2727177ce702511b4842f6f390b6672293d677b3caa8fc77f81377b99fc03380c5918fcee2539e98d7400d1b7e40260ac3b101e3fe963de6c61284aeeb75

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
